apiVersion: v1
kind: Service
metadata:
  name: mrdevops-service
spec:
  selector:
    app: mrdevops
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      
